name: Vulnerability scan

on: [push, pull_request]

jobs:
  vulnerabilities-scan:
    runs-on: ubuntu-latest
    env:
      DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Debricked scan
        uses: debricked/actions/scan@v1

